// Caresse Dashboard feature set — kept in Dashboard folder.
function renderCaresseDashboard(){
 const m=document.getElementById('caresseDashboardMount');if(!m)return;
 const profile=state.registration?.caresse||{};
 m.innerHTML=`<div class="dash-top"><div><p class="muted">● Your interface is set to high-focus mode.</p><h1>Welcome back, ${profile.nickname||profile.name||'there'}! 🌿</h1></div><span class="demo-pill">⚡ Demo Shift</span></div><div class="course-progress"><div><span>◉ In Progress</span><b>Lesson 2 of 5</b></div><strong>64% complete</strong><div class="progress"><i style="width:64%"></i></div><h2>Continue Photosynthesis</h2><p>Light-dependent reactions, photolysis &amp; ATP synthesis mechanics.</p><div class="lesson-image"></div><button class="btn btn-primary btn-block" onclick="showCaresseScreen('screen-caresse-learn')">▶ Resume Lesson <span>🔊</span></button></div>
 <div class="section-heading"><h2>Adaptive Health</h2><span>◌ Real-time biometrics</span></div><div class="metric-grid"><div><small>Current Streak 🔥</small><strong>5 Days</strong><span>Calm consistency peak</span></div><div><small>Focus Score</small><strong>84%</strong><span>Optimal balance</span></div><div><small>Active Mode</small><strong>Visual &amp; Chunked</strong><span>Reduced distractions</span></div><div><small>Today's Time</small><strong>28 mins</strong><span>Target: 35 mins</span></div></div>
 <div class="section-heading"><h2>My Active Courses</h2><span>View all ›</span></div><div class="course-list"><div><span class="course-tag">BIOLOGY</span><h3>Plant Energetics</h3><p>Overall Progress</p><div class="progress"><i style="width:64%"></i></div><small>12 of 18 chapters</small><button onclick="showCaresseScreen('screen-caresse-learn')">Open Module →</button></div><div><span class="course-tag">NEUROSCIENCE</span><h3>Cognitive Psychology</h3><p>Overall Progress</p><div class="progress"><i style="width:40%"></i></div><small>Next: Working Memory Buffers</small><button onclick="showCaresseScreen('screen-caresse-learn')">Review →</button></div><div><span class="course-tag">ECOLOGY</span><h3>Environmental Chemistry</h3><p>Overall Progress</p><div class="progress"><i style="width:18%"></i></div><small>Next: Nitrogen Cycle</small><button onclick="showCaresseScreen('screen-caresse-learn')">Fresh Start →</button></div></div>
 <div class="suggestion-card"><div><h3>🧩 MICRO-PACING</h3><strong>Suggested for Your Rhythm</strong><p>Low-friction 6-minute modules designed for calm executive processing.</p></div><div class="suggestion-item">💡 Calvin Cycle in 3 Sketches <small>Biology · 5 min quick review</small></div><div class="suggestion-item">◉ Phonological Loop Soundbite <small>Cognitive · 4 min audio explainer</small></div><div class="suggestion-item">⚗ Chemical Equilibrium Balance <small>Chemistry · 5 min interactive</small></div><button class="btn btn-primary btn-block" onclick="alert('Demo mode: trigger adaptation')">⚡ Quick Demo Mode: Trigger Adaptation</button></div>
 <div class="telemetry-grid"><div class="telemetry-card"><span class="eyebrow-pill">ADAPTIVE STATE MACHINE</span><h2>Chunked Reading <small>view agenda</small></h2><p>Baseline signals favor predictable chunked reading.</p><div class="rule-box"><b>account_tree</b> Autonomous branch rules<div class="rule-cols"><span>Hesitation<br><strong>High → Flashcards</strong></span><span>Reading speed<br><strong>&lt; 90 WPM → Audio</strong></span><span>Focus score<br><strong>&lt; 55% → Bionic</strong></span></div></div><div class="trigger">⚡ Adaptation triggered · Bionic Reading → Chunked Reading</div></div><div class="telemetry-card"><span class="eyebrow-pill">INTERACTIVE TELEMETRY ADJUSTER</span><h2>Change signals, trigger adaptation</h2><p>These are synthetic interaction indicators for the demo—not clinical measurements.</p><div class="range-row"><label>Reading speed <b>119 WPM</b><input type="range" min="40" max="220" value="119"></label><label>Hesitation level <b>Low</b><input type="range" min="0" max="100" value="20"></label><label>Focus score <b>78%</b><input type="range" min="25" max="100" value="78"></label></div><div class="telemetry-actions"><button class="btn btn-primary" onclick="alert('Distraction simulated → chunked reading enabled')">Simulate distraction</button><button class="btn btn-outline" onclick="alert('Visual preference simulated')">Simulate visual preference</button><button class="btn btn-outline" onclick="alert('Slow reading simulated')">Simulate slow reading</button></div></div></div>`;
}
function updateCaresseNav(id){document.querySelectorAll('#caresseBottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));}
