// Caresse Learn feature set — kept in Learn folder.
let learnMode='chunked'; let learnQuizChoice=''; let learnChunk=0;
const chunks=['Photosynthesis captures light energy and uses water and carbon dioxide to produce glucose and oxygen.','Chlorophyll helps absorb the light energy needed to begin the process.','During the light-dependent reactions, water is split and ATP and NADPH are produced.','The Calvin cycle uses these energy carriers to help build carbohydrates.'];
function setLearnMode(m){learnMode=m; renderCaresseLearn();}
function renderCaresseLearn(){
 const m=document.getElementById('caresseLearnMount');if(!m)return;
 const text=chunks[learnChunk];
 m.innerHTML=`<div class="learn-shell"><div class="learn-hero"><div><div class="chips"><span>Biology · Module 3</span><span>Adaptive pace</span></div><h1>Introduction to Photosynthesis</h1><p>Unit 3: Energy Transfer in Cellular Plant Ecosystems</p><div class="learn-tabs"><button class="selected" onclick="setLearnMode('chunked')">Chunked Reading</button><button onclick="setLearnMode('flashcards')">Flashcards</button><button onclick="setLearnMode('map')">Concept Map</button><button onclick="setLearnMode('audio')">Audio</button><button onclick="setLearnMode('quiz')">Quiz</button></div></div><div class="session-focus"><small>Session focus</small><strong>94%</strong><span>steady</span></div></div>
 <div class="live-adapt"><div><strong>↔ LIVE ADAPTATION</strong><h2>FocusFlow is watching the interface — not you.</h2><p>It uses lightweight interaction signals such as scroll pauses and inactivity to adjust presentation. It does not diagnose attention or learning conditions.</p></div><button class="btn btn-outline" onclick="alert('Demo: a hesitation signal was simulated.')">Simulate hesitation</button><div class="adapt-stats"><span><b>67 px/s</b><small>scroll speed</small></span><span><b>1</b><small>hesitations</small></span><span><b>6s</b><small>idle</small></span></div></div>
 <div class="learn-grid"><div class="learn-main">${learnMode==='map'?conceptMap():learnMode==='quiz'?quizCard():learnMode==='flashcards'?flashcard():learnMode==='audio'?audioCard():chunkCard(text)}</div><aside>${simulatorCard()}${transformCard()}</aside></div></div>`;
}
function chunkCard(text){return `<div class="learn-card key-concept"><div class="key-pill">Key concept · 01 <span>~2 min</span></div><h2>Light energy → chemical fuel</h2><div class="definition"><strong>Photosynthesis</strong> is the biological pipeline where green plants, algae, and cyanobacteria absorb photons from sunlight and convert water and carbon dioxide into storable chemical sugars.</div><div class="plant-visual">⌁<strong>Chloroplast · Thylakoid · Stroma</strong></div><div class="io"><div><small>Inputs</small><strong>Light + H₂O + CO₂</strong></div><div><small>Outputs</small><strong>Glucose + O₂</strong></div></div><div class="listen-back"><div><strong>ListenBack</strong><small>Native browser narration · no audio file required</small></div><p>${text}</p><button class="btn btn-primary" onclick="speak('${text.replace(/'/g,"\\'")}')">▶ Play</button></div><div class="chunk-nav"><button class="btn btn-outline" onclick="learnChunk=Math.max(0,learnChunk-1);renderCaresseLearn()">← Previous</button><span>Chunk ${learnChunk+1} of ${chunks.length}</span><button class="btn btn-primary" onclick="learnChunk=Math.min(chunks.length-1,learnChunk+1);renderCaresseLearn()">Next →</button></div></div>`}
function conceptMap(){return `<div class="learn-card"><h2>Interactive Concept Map</h2><div class="concept-map"><span class="node sun">Sunlight<br><small>photons</small></span><span class="node water">Water<br><small>H₂O</small></span><span class="node center">PHOTOSYNTHESIS<br><small>central flow</small></span><span class="node carbon">Carbon<br><small>CO₂</small></span><span class="node chlor">Chlorophyll<br><small>pigment</small></span><span class="node glucose">Glucose</span></div><div class="map-tip">ⓘ Tap a node to explore relationships without leaving the learning flow.</div></div><div class="learn-card"><h3>Spaced Retrieval</h3><div class="retrieval"><small>PROMPT</small><strong>What is the primary organic molecule synthesized during photosynthesis?</strong><div><button class="btn btn-outline" onclick="alert('Answer: Glucose')">Review Later</button><button class="btn btn-primary" onclick="alert('Correct — glucose')">✓ Got it down</button></div></div></div>`}
function quizCard(){return `<div class="learn-card"><span class="check-pill">Check comprehension</span><h2>Which process allows green plants to produce glucose using sunlight?</h2>${['Cellular respiration','Photosynthesis','Digestion','Transpiration'].map((x,i)=>`<button class="quiz-option ${learnQuizChoice===x?'picked':''}" onclick="learnQuizChoice='${x}';renderCaresseLearn()">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}${learnQuizChoice?`<p class="quiz-feedback">${learnQuizChoice==='Photosynthesis'?'✓ Correct.':'Try again — look for the process driven by light energy.'}</p>`:''}<div class="adaptive-note">✦ Adaptive Engine · A reading pause was detected, so the engine is keeping the current chunk simple.</div></div>`}
function flashcard(){return `<div class="learn-card"><h2>Flashcards</h2><div class="flashcard" onclick="this.classList.toggle('flip')"><div><small>TERM</small><strong>Chlorophyll</strong><span>Tap to reveal</span></div><div><small>MEANING</small><strong>A pigment that absorbs light energy.</strong></div></div><button class="btn btn-outline" onclick="alert('Card saved for spaced retrieval.')">Review later</button></div>`}
function audioCard(){return `<div class="learn-card"><h2>ListenBack</h2><p>Native browser narration — no audio file required.</p><div class="audio-player"><button class="btn btn-primary" onclick="speak('Photosynthesis captures light energy and uses water and carbon dioxide to produce glucose and oxygen.')">▶ Play</button><button class="btn btn-outline" onclick="speechSynthesis?.pause()">Ⅱ Pause</button><button class="btn btn-outline" onclick="speechSynthesis?.cancel()">■ Stop</button></div><div class="audio-track"></div><p class="muted">Ready to narrate</p></div>`}
function simulatorCard(){return `<div class="learn-card simulator"><h3>Interactive cognitive simulator</h3><p>Switch presentation modes and see the dashboard respond instantly.</p><div class="mode-grid"><button onclick="setLearnMode('chunked')">B<br><small>Bionic Reading</small></button><button class="active" onclick="setLearnMode('chunked')">F<br><small>Focus Tint</small></button><button onclick="setLearnMode('chunked')">R<br><small>Reading Mask</small></button></div><div class="capacity"><span>Energy &amp; capacity</span><b>Medium</b><input type="range" min="1" max="3" value="2"></div></div>`}
function transformCard(){return `<div class="learn-card"><h3>Quick Transform</h3><p>Turn walls of text into chunks.</p><div class="transform"><div>Photosynthesis is the process by which green plants convert light energy into chemical energy. During the light-dependent reactions, water is split and ATP and NADPH are produced.</div><div class="adapted-list"><b>1</b> Key idea: light energy becomes chemical energy.<b>2</b> Key idea: chlorophyll absorbs light.<b>3</b> Key idea: ATP and NADPH are produced.</div></div><button class="btn btn-primary btn-block" onclick="alert('Text converted into 3 adaptive chunks.')">Convert to chunks</button></div>`}
