// Caresse Accessibility feature set — kept in Accessibility folder.
const caresseA11y = { focus:false, chunk:true, bionic:false, ruler:false, oneThing:false, font:'standard', size:'16', spacing:'1.8', letters:'normal', theme:'clean', motion:false, tint:'off', speech:true, cadence:1, autoChunk:true, recap:true, breaks:false, telemetry:true };
function toggleA11y(key){ caresseA11y[key]=!caresseA11y[key]; renderCaresseAccessibility(); }
function setA11y(key,val){ caresseA11y[key]=val; renderCaresseAccessibility(); }
function a11yButton(label,key,val){ const active=caresseA11y[key]===val; return `<button class="seg-btn ${active?'selected':''}" onclick="setA11y('${key}','${val}')">${label}</button>`; }
function renderCaresseAccessibility(){
 const m=document.getElementById('caresseAccessibilityMount'); if(!m)return;
 m.innerHTML=`<div class="feature-top"><div><span class="eyebrow-pill">Caresse</span><h1>Accessibility</h1><p>Turn the interface—or let interaction patterns suggest support.</p></div><div class="feature-top-actions"><span class="score-pill">Focus 78%</span><button class="btn btn-primary" onclick="setA11y('telemetry',!caresseA11y.telemetry)">↻ Sync</button></div></div>
 <div class="adaptive-banner"><div><strong>♧ LIVE ADAPTIVE ENGINE</strong><h2>Your interface is responding to your interaction patterns.</h2><p>These are interaction signals, not a medical or cognitive diagnosis.</p></div><div class="mini-stats"><span><b>Comfortable</b><strong>78 / 100</strong></span><span><b>Dwell</b><strong>9s</strong></span><span><b>Scroll</b><strong>9 px/s</strong></span><span><b>Idle</b><strong>0s</strong></span></div></div>
 <div class="a11y-grid">
  <div class="a11y-card"><div class="card-title-row"><div><h3>Focus Mode</h3><p>Reduce peripheral distraction and follow the current reading line.</p></div><button class="switch ${caresseA11y.focus?'on':''}" onclick="toggleA11y('focus')"><i></i></button></div><div class="sandbox"><small>LIVE READING SANDBOX</small><strong>Adaptive interface can reduce unnecessary friction by changing how information is presented.</strong><p>When you pause, hesitate, or repeatedly reverse the reading line, the engine can offer smaller chunks, stronger visual anchors, and optional audio support.</p></div></div>
  <div class="a11y-card"><h3>🪄 Adaptive Reading Tools</h3><p>Transform dense content without changing its meaning.</p><div class="seg-grid">${a11yButton('▤ Auto-Chunk Text','chunk',true)}${a11yButton('B Bionic Reading','bionic',true)}${a11yButton('— Focus Ruler','ruler',true)}${a11yButton('▣ One Thing at a Time','oneThing',true)}</div><p class="sample-reading ${caresseA11y.bionic?'bionic':''}">Photosynthesis is the process by which green plants convert light energy into chemical energy. Chlorophyll captures light, while carbon dioxide and water are used to produce glucose and oxygen.</p></div>
  <div class="a11y-card"><h3> Tᵀ Typography &amp; Reading</h3><p>Choose a visual rhythm that feels comfortable.</p><label>Font family</label><div class="seg-grid three">${a11yButton('Standard','font','standard')}${a11yButton('Dyslexia-friendly','font','dyslexia')}${a11yButton('Mono','font','mono')}</div><label>Font size</label><div class="seg-grid four">${['14','16','18','20'].map(x=>a11yButton(x,'size',x)).join('')}</div><label>Line spacing</label><div class="seg-grid three">${['1.4','1.8','2.2'].map(x=>a11yButton(x,'spacing',x)).join('')}</div><label>Letter spacing</label><div class="seg-grid three">${a11yButton('Normal','letters','normal')}${a11yButton('Wide','letters','wide')}${a11yButton('Extra wide','letters','extra')}</div></div>
  <div class="a11y-card"><h3>◉ Visual &amp; Sensory</h3><p>High-contrast themes and reduced motion.</p><label>Theme</label><div class="seg-grid three">${a11yButton('Clean','theme','clean')}${a11yButton('Warm','theme','warm')}${a11yButton('Calm Dark','theme','dark')}</div><div class="seg-grid one">${a11yButton('High Contrast','theme','contrast')}</div><div class="toggle-row"><span><b>Reduce motion</b><small>Honors system preference and removes non-essential animation.</small></span><button class="switch ${caresseA11y.motion?'on':''}" onclick="toggleA11y('motion')"><i></i></button></div><label>Screen tint</label><div class="seg-grid four">${['off','yellow','mint','rose'].map(x=>a11yButton(x[0].toUpperCase()+x.slice(1),'tint',x)).join('')}</div></div>
  <div class="a11y-card"><h3>🔊 Audio Assistance</h3><p>Native browser speech with simple playback controls.</p><div class="audio-row"><span><b>Text-to-Speech</b><small>Read the learning sample aloud.</small></span><button class="switch ${caresseA11y.speech?'on':''}" onclick="toggleA11y('speech')"><i></i></button></div><div class="audio-controls"><button class="btn btn-primary" onclick="speak('Photosynthesis is the process by which green plants convert light energy into chemical energy.')">▶ Play</button><button class="btn btn-outline" onclick="window.speechSynthesis?.pause()">Ⅱ Pause</button><button class="btn btn-outline" onclick="window.speechSynthesis?.cancel()">■ Stop</button></div><label>Cadence <b class="range-value">${caresseA11y.cadence.toFixed(1)}×</b></label><input type="range" min="0.7" max="1.4" step="0.1" value="${caresseA11y.cadence}" oninput="setA11y('cadence',Number(this.value))"></div>
  <div class="a11y-card wide-card"><h3>⚙ Adaptive Controls</h3><p>Gentle automations that can be overridden at any time.</p><div class="control-grid">${[['autoChunk','Auto-chunk when support rises','Suggests smaller reading units after hesitation.'],['recap','Smart recap','Shows a short recap after a section.'],['breaks','Gentle break suggestion','Optional reminder after prolonged inactivity.'],['telemetry','Telemetry sync','Sends lightweight interaction metrics to your local server.']].map(([k,t,d])=>`<div class="toggle-row"><span><b>${t}</b><small>${d}</small></span><button class="switch ${caresseA11y[k]?'on':''}" onclick="toggleA11y('${k}')"><i></i></button></div>`).join('')}</div></div>
 </div><div class="reset-card"><div><h3>Reset profile</h3><p>Restore the default accessibility configuration stored in this browser.</p></div><button class="btn btn-outline" onclick="Object.assign(caresseA11y,{focus:false,chunk:true,bionic:false,ruler:false,oneThing:false,font:'standard',size:'16',spacing:'1.8',letters:'normal',theme:'clean',motion:false,tint:'off',speech:true,cadence:1,autoChunk:true,recap:true,breaks:false,telemetry:true});renderCaresseAccessibility()">Restore defaults</button></div>`;
}
